DROP TABLE IF EXISTS USER_ROLE_DETAIL;
DROP TABLE IF EXISTS COMMENT_ATTACHMENT;
DROP TABLE IF EXISTS ENTRY_ATTACHMENT;
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS ENTRY;
DROP TABLE IF EXISTS APP_USER;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS ROLE;

CREATE TABLE ROLE (
       ID INT NOT NULL AUTO_INCREMENT
     , ROLE_NAME VARCHAR(50) NOT NULL
     , DESCRIPTION VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE Category (
       ID INT NOT NULL AUTO_INCREMENT
     , CATEGORY_NAME VARCHAR(50) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE APP_USER (
       ID INT NOT NULL AUTO_INCREMENT
     , EMAIL VARCHAR(255) NOT NULL
     , PASSWORD VARCHAR(255) NOT NULL
     , USER_NAME VARCHAR(50)
     , CREATED_BY VARCHAR(255)
     , CREATED_DATE DATETIME
     , LAST_MODIFIED_BY VARCHAR(255)
     , LAST_MODIFIED_DATE DATETIME
     , PRIMARY KEY (ID)
);

CREATE TABLE ENTRY (
       ID INT NOT NULL AUTO_INCREMENT
     , CATEGORY_ID INT
     , SUBJECT VARCHAR(255) NOT NULL
     , BODY VARCHAR(2000) NOT NULL
     , POST_DATE DATETIME NOT NULL
     , CREATED_BY VARCHAR(255)
     , CAEATED_DATE DATETIME
     , LAST_MODIFIED_BY VARCHAR(255)
     , LAST_MODIFIED_DATE DATETIME
     , PRIMARY KEY (ID)
);

CREATE TABLE COMMENT (
       ID INT NOT NULL AUTO_INCREMENT
     , ENTRY_ID INT NOT NULL
     , BODY VARCHAR(2000) NOT NULL
     , POST_BY VARCHAR(255) NOT NULL
     , POST_DATE DATETIME NOT NULL
     , CREATED_BY VARCHAR(255)
     , CREATED_DATE DATETIME
     , LAST_MODIFIED_BY VARCHAR(255)
     , LAST_MODIFIED_DATE DATETIME
     , PRIMARY KEY (ID)
);

CREATE TABLE ENTRY_ATTACHMENT (
       ID INT NOT NULL AUTO_INCREMENT
     , ENTRY_ID INT NOT NULL
     , FILE_NAME VARCHAR(255) NOT NULL
     , FILE_PATH VARCHAR(255) NOT NULL
     , CONTENT_TYPE VARCHAR(10) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE COMMENT_ATTACHMENT (
       ID INT NOT NULL AUTO_INCREMENT
     , COMMENT_ID INT NOT NULL
     , FILE_NAME VARCHAR(255) NOT NULL
     , FILE_PATH VARCHAR(255) NOT NULL
     , CONTENT_TYPE VARCHAR(10) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE_DETAIL (
       USER_ID INT NOT NULL
     , ROLE_ID INT NOT NULL
     , PRIMARY KEY (USER_ID, ROLE_ID)
);

ALTER TABLE ENTRY
  ADD CONSTRAINT FK_ENTRY_1
      FOREIGN KEY (CATEGORY_ID)
      REFERENCES Category (ID);

ALTER TABLE COMMENT
  ADD CONSTRAINT FK_COMMENT_1
      FOREIGN KEY (ENTRY_ID)
      REFERENCES ENTRY (ID);

ALTER TABLE ENTRY_ATTACHMENT
  ADD CONSTRAINT FK_ENTRY_ATTACHMENT_1
      FOREIGN KEY (ENTRY_ID)
      REFERENCES ENTRY (ID);

ALTER TABLE COMMENT_ATTACHMENT
  ADD CONSTRAINT FK_COMMENT_ATTACHMENT_1
      FOREIGN KEY (COMMENT_ID)
      REFERENCES COMMENT (ID);

ALTER TABLE USER_ROLE_DETAIL
  ADD CONSTRAINT FK_USER_ROLE_DETAIL_1
      FOREIGN KEY (USER_ID)
      REFERENCES APP_USER (ID);

ALTER TABLE USER_ROLE_DETAIL
  ADD CONSTRAINT FK_USER_ROLE_DETAIL_2
      FOREIGN KEY (ROLE_ID)
      REFERENCES ROLE (ID);

